"""
artifacts.py — ArtifactWriter generates Markdown reports for self-healing events.

Two artifact types:
  1. AdaptationPlanArtifact  — written when a selector fails and healing begins.
  2. VerificationArtifact    — written after a healed selector is confirmed.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from src.utils.logger import get_logger

log = get_logger("ArtifactWriter")

_ARTIFACT_DIR = Path(__file__).resolve().parents[2] / "artifacts"


def _timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")


def _ensure_dir() -> Path:
    _ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    return _ARTIFACT_DIR


class ArtifactWriter:
    """
    Generates human-readable Markdown artifacts documenting the
    self-healing process.

    Usage::

        writer = ArtifactWriter()
        plan_path = writer.write_adaptation_plan(
            url="https://example.com",
            task_label="price",
            failed_selector=".old-price",
            candidate_selectors=[(".new-price", 0.92)],
            reasoning="Vision model identified new element class...",
            screenshot_path="artifacts/screenshots/before_heal.png",
        )
        verify_path = writer.write_verification(
            url="https://example.com",
            task_label="price",
            selector=".new-price",
            extracted_data="$19.99",
            screenshot_path="artifacts/screenshots/after_heal.png",
            success=True,
        )
    """

    def __init__(self, artifact_dir: Path | str | None = None):
        self._dir = Path(artifact_dir) if artifact_dir else _ensure_dir()
        self._dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------ #
    # Adaptation Plan
    # ------------------------------------------------------------------ #

    def write_adaptation_plan(
        self,
        url: str,
        task_label: str,
        failed_selector: str,
        candidate_selectors: list[tuple[str, float]],
        reasoning: str,
        screenshot_path: Optional[Path | str] = None,
        page_source_snippet: str = "",
    ) -> Path:
        """
        Write an Adaptation Plan artifact detailing why the old selector failed
        and what candidates were proposed by the vision model.

        :returns: Path to the written Markdown file.
        """
        ts = _timestamp()
        filename = f"adaptation_plan_{task_label}_{ts}.md"
        out_path = self._dir / filename

        # Build candidate table
        candidate_rows = "\n".join(
            f"| `{sel}` | {conf:.2%} |"
            for sel, conf in candidate_selectors
        )

        # Screenshot embed (relative path from artifact dir)
        screenshot_section = ""
        if screenshot_path:
            rel = Path(screenshot_path).resolve()
            screenshot_section = f"\n## 📸 Screenshot at Time of Failure\n\n![Page at failure]({rel})\n"

        # Page source snippet
        source_section = ""
        if page_source_snippet:
            trimmed = page_source_snippet[:2000] + ("…" if len(page_source_snippet) > 2000 else "")
            source_section = f"\n## 🔍 Page Source Snippet\n\n```html\n{trimmed}\n```\n"

        content = f"""# 🩺 Adaptation Plan Artifact

> **Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}
> **Task:** `{task_label}`
> **Target URL:** {url}

---

## ❌ Selector Failure Report

| Field | Value |
|---|---|
| **Failed Selector** | `{failed_selector}` |
| **URL** | `{url}` |
| **Task Label** | `{task_label}` |

---
{screenshot_section}
## 🤖 Vision-Model Reasoning

{reasoning}

---

## 🎯 Candidate Selectors (Ranked by Confidence)

| Selector | Confidence |
|---|---|
{candidate_rows}
{source_section}
---

## 📋 Next Steps

1. The agent will attempt each candidate selector in order of confidence.
2. The first successful match will be stored in `data/selector_store.json`.
3. A **Verification Artifact** will be generated upon confirmation.

---
*Auto-generated by Self-Healing Web Agent*
"""

        out_path.write_text(content, encoding="utf-8")
        log.info("Adaptation Plan written → %s", out_path)

        # Also write a JSON companion for programmatic consumption
        json_path = out_path.with_suffix(".json")
        json_path.write_text(
            json.dumps(
                {
                    "type": "adaptation_plan",
                    "timestamp": ts,
                    "url": url,
                    "task_label": task_label,
                    "failed_selector": failed_selector,
                    "candidates": [
                        {"selector": s, "confidence": c}
                        for s, c in candidate_selectors
                    ],
                    "reasoning": reasoning,
                    "screenshot_path": str(screenshot_path) if screenshot_path else None,
                },
                indent=2,
            ),
            encoding="utf-8",
        )

        return out_path

    # ------------------------------------------------------------------ #
    # Verification Artifact
    # ------------------------------------------------------------------ #

    def write_verification(
        self,
        url: str,
        task_label: str,
        selector: str,
        extracted_data: str | list,
        screenshot_path: Optional[Path | str] = None,
        success: bool = True,
        notes: str = "",
    ) -> Path:
        """
        Write a Verification artifact confirming whether the healed selector works.

        :returns: Path to the written Markdown file.
        """
        ts = _timestamp()
        status_emoji = "✅" if success else "❌"
        status_label = "SUCCESS" if success else "FAILURE"
        filename = f"verification_{task_label}_{ts}.md"
        out_path = self._dir / filename

        # Data sample display
        if isinstance(extracted_data, list):
            data_display = "\n".join(f"- `{item}`" for item in extracted_data[:10])
            if len(extracted_data) > 10:
                data_display += f"\n- *(…and {len(extracted_data) - 10} more)*"
        else:
            data_display = f"`{extracted_data}`"

        # Screenshot embed
        screenshot_section = ""
        if screenshot_path:
            rel = Path(screenshot_path).resolve()
            screenshot_section = f"\n## 📸 Verification Screenshot\n\n![Post-heal screenshot]({rel})\n"

        notes_section = f"\n## 📝 Notes\n\n{notes}\n" if notes else ""

        content = f"""# {status_emoji} Verification Artifact — {status_label}

> **Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}
> **Task:** `{task_label}`
> **Target URL:** {url}

---

## 🔬 Verification Summary

| Field | Value |
|---|---|
| **Status** | {status_emoji} **{status_label}** |
| **Verified Selector** | `{selector}` |
| **URL** | `{url}` |
| **Task Label** | `{task_label}` |

---

## 📊 Extracted Data Sample

{data_display}
{screenshot_section}{notes_section}
---

## 💾 Learning Record

The selector `{selector}` has been {"stored in" if success else "rejected from"} `data/selector_store.json`.

---
*Auto-generated by Self-Healing Web Agent*
"""

        out_path.write_text(content, encoding="utf-8")
        log.info("Verification Artifact written → %s", out_path)

        # JSON companion
        json_path = out_path.with_suffix(".json")
        json_path.write_text(
            json.dumps(
                {
                    "type": "verification",
                    "timestamp": ts,
                    "url": url,
                    "task_label": task_label,
                    "selector": selector,
                    "success": success,
                    "extracted_data": extracted_data,
                    "screenshot_path": str(screenshot_path) if screenshot_path else None,
                    "notes": notes,
                },
                indent=2,
            ),
            encoding="utf-8",
        )

        return out_path
